spring.datasource.url=jdbc:postgresql://localhost:5432/recipe_book
spring.datasource.username=postgres
spring.datasource.password=pos
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=12MB

recipebook.public-base-url=http://localhost:8080
recipebook.storage.dish-photos-dir=uploads/dish-photos
recipebook.storage.product-photos-dir=uploads/product-photos
